Repository icsharpcode/ILSpy, pull requests merged in 2020-08, with the labels that each got.

#2066 All the new statements has been translated
  BuildTools/sort-resx.ps1
  ILSpy.AddIn/ILSpy.AddIn.csproj
  ILSpy.AddIn/ILSpyAddIn.en-US.vsct
  ILSpy.AddIn/ILSpyAddIn.vsct
  ILSpy.AddIn/ILSpyAddIn.zh-Hans.vsct
  ILSpy.AddIn/ILSpyAddInPackage.cs
  ILSpy.AddIn/Properties/AssemblyInfo.cs
  ILSpy.AddIn/VSPackage.en-US.resx
  ILSpy.AddIn/VSPackage.zh-Hans.resx
  ILSpy.AddIn/zh-Hans/extension.vsixlangpack
  ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
  ILSpy.ReadyToRun/Properties/AssemblyInfo.cs
  ILSpy.ReadyToRun/Properties/Resources.Designer.cs
  ILSpy.ReadyToRun/Properties/Resources.resx
  ILSpy.ReadyToRun/Properties/Resources.zh-Hans.resx
  ILSpy.ReadyToRun/ReadyToRunLanguage.cs
  ILSpy.ReadyToRun/ReadyToRunOptionPage.xaml
  ILSpy.ReadyToRun/ReadyToRunOptionPage.xaml.cs
  ILSpy/AboutPage.cs
  ILSpy/Commands/DecompileCommand.cs
  ILSpy/Commands/GeneratePdbContextMenuEntry.cs
  ILSpy/Commands/ManageAssemblyListsCommand.cs
  ILSpy/Commands/Pdb2XmlCommand.cs
  ILSpy/Commands/SaveCodeContextMenuEntry.cs
  ILSpy/Commands/SelectPdbContextMenuEntry.cs
  ILSpy/ILSpy.csproj
  ILSpy/Properties/Resources.Designer.cs
  ILSpy/Properties/Resources.resx
  ILSpy/Properties/Resources.zh-Hans.resx
  appveyor.yml
  doc/ILSpyAboutPage_zh_Hans.txt
Labels: UI, VS Extension

#2067 Adding variable tracking throughout assembly printout
  ILSpy.ReadyToRun/ILSpy.ReadyToRun.csproj
  ILSpy.ReadyToRun/ReadyToRunLanguage.cs
  ILSpy.ReadyToRun/ReadyToRunOptionPage.xaml
  ILSpy.ReadyToRun/ReadyToRunOptionPage.xaml.cs
  ILSpy.ReadyToRun/ReadyToRunOptions.cs
Labels: r2r

#2087 Lock closed issues after defined time period
  .github/workflows/lock.yml
Labels: Build Automation, Enhancement
