Repository icsharpcode/ILSpy, pull requests merged in 2024-12, with the labels that each got.

#3338 Fix for "Unable to locate dotnet CLI. Ensure that it is on the PATH."
  .github/workflows/build-ilspy.yml
  BuildTools/pre-commit
Labels: Build Automation

#3340 Update ReadyToRun to use 9.0 package
  Directory.Packages.props
  ILSpy.ReadyToRun/ReadyToRunLanguage.cs
  NuGet.config
Labels: r2r

#3336 Implement 3330: Generate diagram from UI without advanced options
  ILSpy/Commands/CreateDiagramContextMenuEntry.cs
  ILSpy/Docking/DockWorkspace.cs
  ILSpy/Properties/Resources.Designer.cs
  ILSpy/Properties/Resources.resx
  ILSpy/TextView/DecompilerTextView.cs
Labels: UI, Diagrammer
