Repository icsharpcode/ILSpy, pull requests merged in 2025-07, with the labels that each got.

#3506 Remove NaturalSort.Extension for net10 in-built CompareOptions.NumericOrdering
  Directory.Packages.props
  ILSpy/ILSpy.csproj
  ILSpy/TreeNodes/NaturalStringComparer.cs
  doc/third-party-notices.txt
Labels: UI

#3505 Add dynamic ILSpy settings options to ILSpyCmd
  ICSharpCode.ILSpyCmd/IlspyCmdProgram.cs
  ICSharpCode.ILSpyX/Settings/DecompilerSettings.cs
  ICSharpCode.ILSpyX/Settings/SettingsServiceBase.cs
  ILSpy.ReadyToRun/ReadyToRunOptions.cs
  ILSpy/DecompilationOptions.cs
  ILSpy/LanguageSettings.cs
  ILSpy/Options/DecompilerSettingsViewModel.cs
  ILSpy/Options/DisplaySettings.cs
  ILSpy/SessionSettings.cs
  ILSpy/Updates/UpdateSettings.cs
  ILSpy/Util/SettingsService.cs
  TestPlugin/CustomOptionPage.xaml.cs
Labels: ILSpyCmd

#3507 .NET 10 MTP dotnet test
  .github/workflows/build-ilspy.yml
  .gitignore
  Directory.Build.props
  Directory.Packages.props
  ICSharpCode.Decompiler.Tests/ICSharpCode.Decompiler.Tests.csproj
  ILSpy.BamlDecompiler.Tests/ILSpy.BamlDecompiler.Tests.csproj
  ILSpy.Tests/ILSpy.Tests.csproj
  dotnet.config
Labels: Build Automation, Tests

#3511 .NET 10.0 Preview5 NuGet Updates
  Directory.Packages.props
  ICSharpCode.BamlDecompiler/packages.lock.json
  ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
  ICSharpCode.Decompiler/packages.lock.json
  ICSharpCode.ILSpyCmd/packages.lock.json
  ICSharpCode.ILSpyX/packages.lock.json
Labels: dependencies

#3502 Fix SDK-style (modern) inter-project references
  ICSharpCode.Decompiler/CSharp/ProjectDecompiler/TargetServices.cs
  ICSharpCode.Decompiler/Solution/SolutionCreator.cs
  ILSpy/Commands/SaveCodeContextMenuEntry.cs
  ILSpy/SolutionWriter.cs
Labels: ILSpyCmd
